### ISSUE TITLE
download-assets does not export all assets

### ISSUE THREAD

**Issue by radu-puscasu** [phstudy/dsa-downloader#1]
when running download-assets the out/assets_extracted folder does not contain all assets. As it stands with the current DSA version of 27.4, only 12 folders are generated in this out folder. 

The folder out/assets does seem to contain all assets however.

**Comment by phstudy** [comment]
Hi Urza,
I tried yesterday, and the dsa-downloader can export all assets. 
Do you think using the Docker version for exporting would be more reliable?
